"use strict";
exports.__esModule = true;
var message = "Hello";
console.log(message);
var isStudent;
isStudent = true;
console.log(isStudent);
var age = 25;
console.log(age);
var name = "Himanshu you are " + age + " years old. " + message;
console.log(name);
// let name2 : string = undefined;
// let age2 : number = null;
// let isLogin :boolean = undefined;
var list1 = [1, 2, 3];
var list2 = ["1", "2", "3"];
var list3 = [true, false];
var person1 = ["Himanshu", 25];
// enum myColors {Red, Green, Blue};
var myColors;
(function (myColors) {
    myColors[myColors["Red"] = 5] = "Red";
    myColors[myColors["Green"] = 6] = "Green";
    myColors[myColors["Blue"] = 7] = "Blue";
})(myColors || (myColors = {}));
var color1 = myColors.Green;
console.log("color1", color1);
var anyValue;
anyValue = "himanshu";
var a;
a = "Himanshu";
a = 10;
console.log(a);
var b = 10;
name = 'Aman';
